version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobtracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=jobtracker;Username=postgres;Password=postgres;Port=5432"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      # OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317   # uncomment + add jaeger service to export traces
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      API_URL: http://backend:8080
      NEXT_PUBLIC_API_URL: http://localhost:5000
      DEFAULT_ORG_ID: "00000000-0000-0000-0000-000000000001"
      NEXT_PUBLIC_ORG_ID: "00000000-0000-0000-0000-000000000001"
      OTEL_SERVICE_NAME: "jobtracker-frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
